### ISSUE TITLE
Stuck in "Psalm: starting"

### ISSUE THREAD

**Issue by shaneparsons** [plotbox-io/psalm-docker-vscode#1]
I followed the setup steps to the best of my ability, but the extension is stuck in a "Psalm: starting" state... Here's my config:

<details><summary>settings.json</summary>

```json
  "psalm_docker.dockerServiceName": "dme-app",
  "psalm_docker.localDockerComposePaths": [
    "/home/sparsons/repo/dme/docker-compose.override.yml",
    "/home/sparsons/repo/dme/docker-compose.yml"
  ],
  "psalm_docker.remotePsalmServerPath": "/var/www/html/vendor/bin/psalm-language-server",
  "psalm_docker.localPath": "/home/sparsons/repo/dme",
  "psalm_docker.remotePath": "/var/www/html/",
  "psalm_docker.remotePsalmXmlPath": "/var/www/html/psalm.xml",
  "psalm_docker.debug": true,
```
</details>

Some more details about my environment:

- PHP (`8.1.7`) is running in a container called `dme-app` (details below)
- Psalm (`4.23`) and Xdebug (`3.1.5`) are both running / working in that container
- `psalm` / `psalm-language-server` / `psalm.xml` are present both locally and in the container
  - I'm wondering if this is part of the problem? i.e. maybe the plugin is trying to use the local versions?
- The directory I want to scan is the `src/` directory (i.e. `./vendor/bin/psalm src/`), which is also in that container

<details><summary>docker-compose (relevent parts)</summary>

main:
```yaml
dme-app:
  image: sunteck/dme:dev
  build:
    context: ./
    dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/html/
```
override:
```yaml
dme-app:
  volumes:
    - .vscode/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - .vscode/xdebug.log:/var/log/xdebug.log
  extra_hosts:
    - host.docker.internal:host-gateway
```
</details>

<details><summary>dockerfile (relevent parts)</summary>

```dockerfile
FROM php:8.1-fpm as base

RUN apt-get update && \
    apt-get install -y libpq-dev libxslt-dev

RUN docker-php-ext-install intl opcache xsl pgsql pdo_pgsql sockets
RUN pecl install redis \
    && docker-php-ext-enable redis

COPY . /var/www/html
COPY ./provision/php/memory.ini /usr/local/etc/php/conf.d/
COPY --from=assets /app/public/build/ /var/www/html/public/build/
COPY --from=composer /app/vendor/ /var/www/html/vendor/

RUN mkdir -p public/bundles/ && ./bin/console assets:install
```
</details>

<details><summary>composer.json (relevent parts)</summary>

```json
"psalm/plugin-phpunit": "^0.16.1",
"psalm/plugin-symfony": "^3.1",
"vimeo/psalm": "^4.22",
"weirdan/doctrine-psalm-plugin": "^2.3"
```
</details>

I'm not sure if I just have part of my config wrong, or if something else is not set up right? Psalm does work outside of this plugin, so environment wise everything is good.

I recently set up a similar [phpstan plugin](https://github.com/SanderRonde/phpstan-vscode) by using a `binCommand` parameter:
<details><summary>settings.json</summary>

```json
"phpstan.binCommand": ["php-dme", "vendor/bin/phpstan"],
"phpstan.paths": { "/home/sparsons/repo/dme": "/var/www/html" },
```

`php-dme` is a bin command for `docker-compose run --rm dme-app "$@"`
</details>

Perhaps we need something like that here as well? Maybe something like this already exists and I'm just missing it?

Any help would be greatly appreciated!
